
export const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  ERROR: 'LOGIN_ERROR'
}

export const SIGNUP = {
  REQUEST: 'SIGNUP_REQUEST',
  SUCCESS: 'SIGNUP_SUCCESS',
  ERROR: 'SIGNUP_ERROR'
}

export const LOGOUT = {
  REQUEST: 'LOGOUT_REQUEST',
  SUCCESS: 'LOGOUT_SUCCESS'
}

export const AUTH_TOKEN = {
  SET: 'SET_AUTH_TOKEN',
  REMOVE: 'REMOVE_AUTH_TOKEN',
  USER_AUTHENTICATED: 'AUTH_USER_AUTHENTICATED',
  AUTH_TOKEN_PRESENT: 'AUTH_TOKEN_PRESENT'
}

export const USER = {
  FETCH_REQUEST: 'FETCH_USER_REQUEST',
  FETCH_ERROR: 'FETCH_USER_ERROR',
  FETCH_SUCCESS: 'FETCH_USER_SUCCESS'
}

export const WALLET = {
  SAVE_REQUEST: 'WALLET_SAVE_REQUEST',
  SAVE_SUCCESS: 'WALLET_SAVE_SUCCESS',
  SAVE_ERROR: 'WALLET_SAVE_ERROR',
  FETCH_REQUEST: 'WALLET_FETCH_REQUEST',
  FETCH_SUCCESS: 'WALLET_FETCH_SUCCESS',
  FETCH_ERROR: 'WALLET_FETCH_ERROR',
  FETCH_ALL_REQUEST: 'WALLET_FETCH_ALL_REQUEST',
  FETCH_ALL_SUCCESS: 'WALLET_FETCH_ALL_SUCCESS',
  FETCH_ALL_ERROR: 'WALLET_FETCH_ALL_ERROR'
}

export const FIAT_RATES = {
  FETCH_REQUEST: 'FETCH_FIAT_RATE_REQUEST',
  FETCH_SUCCESS: 'FETCH_FIAT_RATE_SUCCESS',
  FETCH_ERROR: 'FETCH_FIAT_RATE_ERROR',
  FETCH_ALL_REQUEST: 'FETCH_FIAT_RATES_REQUEST',
  FETCH_ALL_SUCCESS: 'FETCH_FIAT_RATES_SUCCESS',
  FETCH_ALL_ERROR: 'FETCH_FIAT_RATES_ERROR',
  FETCH_IP_REQUEST: 'FETCH_FIAT_RATE_IP_REQUEST',
  FETCH_IP_SUCCESS: 'FETCH_FIAT_RATE_IP_SUCCESS',
  FETCH_IP_ERROR: 'FETCH_FIAT_RATE_IP_ERROR',
  SET_DEFAULT_CURRENCY: 'SET_DEFAULT_CURRENCY'
}
